// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestParts_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewParts()

	called := false
	cmd.CommandAction = func(c *Parts) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--input")
	args = append(args, "test")
	args = append(args, "--output")
	args = append(args, "test")
	args = append(args, "--json")
	args = append(args, "--delimiter")
	args = append(args, "test")
	args = append(args, "--number-splitting")
	args = append(args, "--non-alphanumeric")
	args = append(args, "--delimiters-func")
	args = append(args, "test")
	args = append(args, "--strict")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.input != "test" {
		t.Errorf("Expected input to be 'test', got '%v'", cmd.input)
	}
	if cmd.output != "test" {
		t.Errorf("Expected output to be 'test', got '%v'", cmd.output)
	}
	if cmd.jsonOut != true {
		t.Errorf("Expected jsonOut to be true, got '%v'", cmd.jsonOut)
	}
	if cmd.delimiter != "test" {
		t.Errorf("Expected delimiter to be 'test', got '%v'", cmd.delimiter)
	}
	if cmd.numberSplitting != true {
		t.Errorf("Expected numberSplitting to be true, got '%v'", cmd.numberSplitting)
	}
	if cmd.nonAlphanumeric != true {
		t.Errorf("Expected nonAlphanumeric to be true, got '%v'", cmd.nonAlphanumeric)
	}
	if cmd.delimiters != "test" {
		t.Errorf("Expected delimiters to be 'test', got '%v'", cmd.delimiters)
	}
	if cmd.strict != true {
		t.Errorf("Expected strict to be true, got '%v'", cmd.strict)
	}
}

func TestParts_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewParts()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
