// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/strings2/cli"
)

var _ Cmd = (*Parts)(nil)

type Parts struct {
	*RootCmd
	Flags           *flag.FlagSet
	input           string
	output          string
	jsonOut         bool
	delimiter       string
	numberSplitting bool
	nonAlphanumeric bool
	strict          bool
	args            []string
	SubCommands     map[string]Cmd
	CommandAction   func(c *Parts) error
}

type UsageDataParts struct {
	*Parts
	Recursive bool
}

func (c *Parts) Usage() {
	err := executeUsage(os.Stderr, "parts_usage.txt", UsageDataParts{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Parts) UsageRecursive() {
	err := executeUsage(os.Stderr, "parts_usage.txt", UsageDataParts{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Parts) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "input", "i":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.input = value

			case "output", "o":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.output = value

			case "jsonOut", "json":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.jsonOut = b
				} else {
					c.jsonOut = true
				}

			case "delimiter", "d":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.delimiter = value

			case "numberSplitting", "number-splitting":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.numberSplitting = b
				} else {
					c.numberSplitting = true
				}

			case "nonAlphanumeric", "non-alphanumeric", "alphanumeric", "N":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.nonAlphanumeric = b
				} else {
					c.nonAlphanumeric = true
				}

			case "strict":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.strict = b
				} else {
					c.strict = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	// Handle vararg args
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.args = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("parts failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewParts() *Parts {
	set := flag.NewFlagSet("parts", flag.ContinueOnError)
	v := &Parts{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.input, "input", "", "Input file or - for stdin")
	set.StringVar(&v.input, "i", "", "Input file or - for stdin")

	set.StringVar(&v.output, "output", "", "Output file or - for stdout")
	set.StringVar(&v.output, "o", "", "Output file or - for stdout")

	set.BoolVar(&v.jsonOut, "json", false, "Output as JSON")

	set.StringVar(&v.delimiter, "delimiter", "", "Delimiter")
	set.StringVar(&v.delimiter, "d", "", "Delimiter")

	set.BoolVar(&v.numberSplitting, "number-splitting", false, "Enable number splitting")

	set.BoolVar(&v.nonAlphanumeric, "non-alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "N", false, "Treat non characters as delimiters")

	set.BoolVar(&v.strict, "strict", false, "Strict UTF8 mode")
	set.Usage = v.Usage

	v.CommandAction = func(c *Parts) error {

		cli.Parts(c.input, c.output, c.jsonOut, c.delimiter, c.numberSplitting, c.nonAlphanumeric, c.strict, c.args...)
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
