// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/arran4/strings2/cmd/strings2/templates"
)

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data interface{}) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands      map[string]Cmd
	Version       string
	Commit        string
	Date          string
	CommandAction func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	c.PrintDefaults()
	fmt.Fprintln(os.Stderr, "  Commands:")
	for name := range c.Commands {
		fmt.Fprintf(os.Stderr, "    %s\n", name)
	}
}

func (c *RootCmd) UsageRecursive() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	c.PrintDefaults()
	fmt.Fprintln(os.Stderr, "  Commands:")
	fmt.Fprintf(os.Stderr, "    %s\n", "camel")
	fmt.Fprintf(os.Stderr, "    %s\n", "darwin")
	fmt.Fprintf(os.Stderr, "    %s\n", "delimited")
	fmt.Fprintf(os.Stderr, "    %s\n", "kebab")
	fmt.Fprintf(os.Stderr, "    %s\n", "lowercamel")
	fmt.Fprintf(os.Stderr, "    %s\n", "parts")
	fmt.Fprintf(os.Stderr, "    %s\n", "pascal")
	fmt.Fprintf(os.Stderr, "    %s\n", "screamingdelimited")
	fmt.Fprintf(os.Stderr, "    %s\n", "screamingkebab")
	fmt.Fprintf(os.Stderr, "    %s\n", "screamingsnake")
	fmt.Fprintf(os.Stderr, "    %s\n", "snake")
	fmt.Fprintf(os.Stderr, "    %s\n", "subparts")
	fmt.Fprintf(os.Stderr, "    %s\n", "title")
	fmt.Fprintf(os.Stderr, "    %s\n", "words")
	fmt.Fprintf(os.Stderr, "    %s\n", "wordstocamel")
	fmt.Fprintf(os.Stderr, "    %s\n", "wordstodarwin")
	fmt.Fprintf(os.Stderr, "    %s\n", "wordstokebab")
	fmt.Fprintf(os.Stderr, "    %s\n", "wordstopascal")
	fmt.Fprintf(os.Stderr, "    %s\n", "wordstosnake")
	fmt.Fprintf(os.Stderr, "    %s\n", "wordstotitle")
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:  flag.NewFlagSet(name, flag.ExitOnError),
		Commands: make(map[string]Cmd),
		Version:  version,
		Commit:   commit,
		Date:     date,
	}
	c.FlagSet.Usage = c.Usage

	c.Commands["camel"] = c.NewCamel()
	c.Commands["darwin"] = c.NewDarwin()
	c.Commands["delimited"] = c.NewDelimited()
	c.Commands["kebab"] = c.NewKebab()
	c.Commands["lowercamel"] = c.NewLowercamel()
	c.Commands["parts"] = c.NewParts()
	c.Commands["pascal"] = c.NewPascal()
	c.Commands["screamingdelimited"] = c.NewScreamingdelimited()
	c.Commands["screamingkebab"] = c.NewScreamingkebab()
	c.Commands["screamingsnake"] = c.NewScreamingsnake()
	c.Commands["snake"] = c.NewSnake()
	c.Commands["subparts"] = c.NewSubparts()
	c.Commands["title"] = c.NewTitle()
	c.Commands["words"] = c.NewWords()
	c.Commands["wordstocamel"] = c.NewWordstocamel()
	c.Commands["wordstodarwin"] = c.NewWordstodarwin()
	c.Commands["wordstokebab"] = c.NewWordstokebab()
	c.Commands["wordstopascal"] = c.NewWordstopascal()
	c.Commands["wordstosnake"] = c.NewWordstosnake()
	c.Commands["wordstotitle"] = c.NewWordstotitle()
	c.Commands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					c.UsageRecursive()
					return nil
				}
			}
			c.Usage()
			return nil
		},
		UsageFunc: c.Usage,
	}
	c.Commands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					c.UsageRecursive()
					return nil
				}
			}
			c.Usage()
			return nil
		},
		UsageFunc: c.Usage,
	}
	c.Commands["version"] = &InternalCommand{
		Exec: func(args []string) error {
			fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
			return nil
		},
		UsageFunc: func() {
			fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
		},
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) error {
	if err := c.Parse(args); err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.Args()
	if len(remainingArgs) < 1 {
		c.Usage()
		return nil
	}
	cmd, ok := c.Commands[remainingArgs[0]]
	if !ok {
		c.Usage()
		return fmt.Errorf("unknown command: %s", remainingArgs[0])
	}
	return cmd.Execute(remainingArgs[1:])
}
