// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestScreamingsnake_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewScreamingsnake()

	called := false
	cmd.CommandAction = func(c *Screamingsnake) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--input")
	args = append(args, "test")
	args = append(args, "--output")
	args = append(args, "test")
	args = append(args, "--delimiter")
	args = append(args, "test")
	args = append(args, "--screaming")
	args = append(args, "--whispering")
	args = append(args, "--first-upper")
	args = append(args, "--first-lower")
	args = append(args, "--mix-case-support")
	args = append(args, "--no-smart-acronyms")
	args = append(args, "--number-splitting")
	args = append(args, "--non-alphanumeric")
	args = append(args, "--delimiters-func")
	args = append(args, "test")
	args = append(args, "--acronym")
	args = append(args, "test")
	args = append(args, "--acronym-from-file")
	args = append(args, "test")
	args = append(args, "--strict")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.input != "test" {
		t.Errorf("Expected input to be 'test', got '%v'", cmd.input)
	}
	if cmd.output != "test" {
		t.Errorf("Expected output to be 'test', got '%v'", cmd.output)
	}
	if cmd.delimiter != "test" {
		t.Errorf("Expected delimiter to be 'test', got '%v'", cmd.delimiter)
	}
	if cmd.screaming != true {
		t.Errorf("Expected screaming to be true, got '%v'", cmd.screaming)
	}
	if cmd.whispering != true {
		t.Errorf("Expected whispering to be true, got '%v'", cmd.whispering)
	}
	if cmd.firstUpper != true {
		t.Errorf("Expected firstUpper to be true, got '%v'", cmd.firstUpper)
	}
	if cmd.firstLower != true {
		t.Errorf("Expected firstLower to be true, got '%v'", cmd.firstLower)
	}
	if cmd.mixCaseSupport != true {
		t.Errorf("Expected mixCaseSupport to be true, got '%v'", cmd.mixCaseSupport)
	}
	if cmd.noSmartAcronyms != true {
		t.Errorf("Expected noSmartAcronyms to be true, got '%v'", cmd.noSmartAcronyms)
	}
	if cmd.numberSplitting != true {
		t.Errorf("Expected numberSplitting to be true, got '%v'", cmd.numberSplitting)
	}
	if cmd.nonAlphanumeric != true {
		t.Errorf("Expected nonAlphanumeric to be true, got '%v'", cmd.nonAlphanumeric)
	}
	if cmd.delimiters != "test" {
		t.Errorf("Expected delimiters to be 'test', got '%v'", cmd.delimiters)
	}
	if cmd.strict != true {
		t.Errorf("Expected strict to be true, got '%v'", cmd.strict)
	}
}

func TestScreamingsnake_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewScreamingsnake()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
