// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestScreamingkebab_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewScreamingkebab()

	called := false
	cmd.CommandAction = func(c *Screamingkebab) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--input")
	args = append(args, "test")
	args = append(args, "--output")
	args = append(args, "test")
	args = append(args, "--delimiter")
	args = append(args, "test")
	args = append(args, "--screaming")
	args = append(args, "--whispering")
	args = append(args, "--firstUpper")
	args = append(args, "--firstLower")
	args = append(args, "--mixCaseSupport")
	args = append(args, "--noSmartAcronyms")
	args = append(args, "--numberSplitting")
	args = append(args, "--acronym")
	args = append(args, "--acronymFromFile")
	args = append(args, "--strict")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.input != "test" {
		t.Errorf("Expected input to be 'test', got '%v'", cmd.input)
	}
	if cmd.output != "test" {
		t.Errorf("Expected output to be 'test', got '%v'", cmd.output)
	}
	if cmd.delimiter != "test" {
		t.Errorf("Expected delimiter to be 'test', got '%v'", cmd.delimiter)
	}
	if cmd.screaming != true {
		t.Errorf("Expected screaming to be true, got '%v'", cmd.screaming)
	}
	if cmd.whispering != true {
		t.Errorf("Expected whispering to be true, got '%v'", cmd.whispering)
	}
	if cmd.firstUpper != true {
		t.Errorf("Expected firstUpper to be true, got '%v'", cmd.firstUpper)
	}
	if cmd.firstLower != true {
		t.Errorf("Expected firstLower to be true, got '%v'", cmd.firstLower)
	}
	if cmd.mixCaseSupport != true {
		t.Errorf("Expected mixCaseSupport to be true, got '%v'", cmd.mixCaseSupport)
	}
	if cmd.noSmartAcronyms != true {
		t.Errorf("Expected noSmartAcronyms to be true, got '%v'", cmd.noSmartAcronyms)
	}
	if cmd.numberSplitting != true {
		t.Errorf("Expected numberSplitting to be true, got '%v'", cmd.numberSplitting)
	}
	if cmd.strict != true {
		t.Errorf("Expected strict to be true, got '%v'", cmd.strict)
	}
}
