// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestSubparts_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewSubparts()

	called := false
	cmd.CommandAction = func(c *Subparts) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--input")
	args = append(args, "test")
	args = append(args, "--output")
	args = append(args, "test")
	args = append(args, "--jsonOut")
	args = append(args, "--strict")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.input != "test" {
		t.Errorf("Expected input to be 'test', got '%v'", cmd.input)
	}
	if cmd.output != "test" {
		t.Errorf("Expected output to be 'test', got '%v'", cmd.output)
	}
	if cmd.jsonOut != true {
		t.Errorf("Expected jsonOut to be true, got '%v'", cmd.jsonOut)
	}
	if cmd.strict != true {
		t.Errorf("Expected strict to be true, got '%v'", cmd.strict)
	}
}
