// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestWordstodarwin_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]Cmd),
	}
	cmd := parent.NewWordstodarwin()

	called := false
	cmd.CommandAction = func(c *Wordstodarwin) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--input")
	args = append(args, "test")
	args = append(args, "--output")
	args = append(args, "test")
	args = append(args, "--jsonInput")
	args = append(args, "--delimiter")
	args = append(args, "test")
	args = append(args, "--screaming")
	args = append(args, "--whispering")
	args = append(args, "--firstUpper")
	args = append(args, "--firstLower")
	args = append(args, "--nonAlphanumeric")
	args = append(args, "--strict")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.input != "test" {
		t.Errorf("Expected input to be 'test', got '%v'", cmd.input)
	}
	if cmd.output != "test" {
		t.Errorf("Expected output to be 'test', got '%v'", cmd.output)
	}
	if cmd.jsonInput != true {
		t.Errorf("Expected jsonInput to be true, got '%v'", cmd.jsonInput)
	}
	if cmd.delimiter != "test" {
		t.Errorf("Expected delimiter to be 'test', got '%v'", cmd.delimiter)
	}
	if cmd.screaming != true {
		t.Errorf("Expected screaming to be true, got '%v'", cmd.screaming)
	}
	if cmd.whispering != true {
		t.Errorf("Expected whispering to be true, got '%v'", cmd.whispering)
	}
	if cmd.firstUpper != true {
		t.Errorf("Expected firstUpper to be true, got '%v'", cmd.firstUpper)
	}
	if cmd.firstLower != true {
		t.Errorf("Expected firstLower to be true, got '%v'", cmd.firstLower)
	}
	if cmd.nonAlphanumeric != true {
		t.Errorf("Expected nonAlphanumeric to be true, got '%v'", cmd.nonAlphanumeric)
	}
	if cmd.strict != true {
		t.Errorf("Expected strict to be true, got '%v'", cmd.strict)
	}
}
