// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"github.com/arran4/strings2/cli"
)

var _ Cmd = (*Wordstosnake)(nil)

type Wordstosnake struct {
	*RootCmd
	Flags           *flag.FlagSet
	input           string
	output          string
	jsonInput       bool
	delimiter       string
	screaming       bool
	whispering      bool
	firstUpper      bool
	firstLower      bool
	nonAlphanumeric bool
	delimiters      string
	strict          bool
	args            []string
	SubCommands     map[string]func() Cmd
	CommandAction   func(c *Wordstosnake) error
}

type UsageDataWordstosnake struct {
	*Wordstosnake
	Recursive bool
}

func (c *Wordstosnake) Usage() {
	err := executeUsage(os.Stderr, "wordstosnake_usage.txt", UsageDataWordstosnake{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Wordstosnake) UsageRecursive() {
	err := executeUsage(os.Stderr, "wordstosnake_usage.txt", UsageDataWordstosnake{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Wordstosnake) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "input":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.input = value

			case "output":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.output = value

			case "jsonInput", "json-input":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.jsonInput = b
				} else {
					c.jsonInput = true
				}

			case "delimiter":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.delimiter = value

			case "screaming":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.screaming = b
				} else {
					c.screaming = true
				}

			case "whispering":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.whispering = b
				} else {
					c.whispering = true
				}

			case "firstUpper", "first-upper":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.firstUpper = b
				} else {
					c.firstUpper = true
				}

			case "firstLower", "first-lower":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.firstLower = b
				} else {
					c.firstLower = true
				}

			case "nonAlphanumeric", "non-alphanumeric", "alphanumeric":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.nonAlphanumeric = b
				} else {
					c.nonAlphanumeric = true
				}

			case "delimiters":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.delimiters = value

			case "strict":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.strict = b
				} else {
					c.strict = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "i" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.input = value
				}

				if char == "o" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.output = value
				}

				if char == "d" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.delimiter = value
				}

				if char == "S" {
					found = true
					c.screaming = true
				}

				if char == "w" {
					found = true
					c.whispering = true
				}

				if char == "U" {
					found = true
					c.firstUpper = true
				}

				if char == "l" {
					found = true
					c.firstLower = true
				}

				if char == "N" {
					found = true
					c.nonAlphanumeric = true
				}

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	// Handle vararg args
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.args = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("wordstosnake failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewWordstosnake() *Wordstosnake {
	set := flag.NewFlagSet("wordstosnake", flag.ContinueOnError)
	v := &Wordstosnake{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.input, "input", "", "Input file or - for stdin")
	set.StringVar(&v.input, "i", "", "Input file or - for stdin")

	set.StringVar(&v.output, "output", "", "Output file or - for stdout")
	set.StringVar(&v.output, "o", "", "Output file or - for stdout")

	set.BoolVar(&v.jsonInput, "json-input", false, "Input as JSON")

	set.StringVar(&v.delimiter, "delimiter", "", "Delimiter")
	set.StringVar(&v.delimiter, "d", "", "Delimiter")

	set.BoolVar(&v.screaming, "screaming", false, "Screaming mode")
	set.BoolVar(&v.screaming, "S", false, "Screaming mode")

	set.BoolVar(&v.whispering, "whispering", false, "Whispering mode")
	set.BoolVar(&v.whispering, "w", false, "Whispering mode")

	set.BoolVar(&v.firstUpper, "first-upper", false, "First char upper")
	set.BoolVar(&v.firstUpper, "U", false, "First char upper")

	set.BoolVar(&v.firstLower, "first-lower", false, "First char lower")
	set.BoolVar(&v.firstLower, "l", false, "First char lower")

	set.BoolVar(&v.nonAlphanumeric, "non-alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "N", false, "Treat non characters as delimiters")

	set.StringVar(&v.delimiters, "delimiters", "", "Delimiters expression")

	set.BoolVar(&v.strict, "strict", false, "Strict UTF8 mode")
	set.Usage = v.Usage

	v.CommandAction = func(c *Wordstosnake) error {

		cli.WordsToSnake(c.input, c.output, c.jsonInput, c.delimiter, c.screaming, c.whispering, c.firstUpper, c.firstLower, c.nonAlphanumeric, c.delimiters, c.strict, c.args...)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
