// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/arran4/strings2/cli"
)

var _ Cmd = (*Wordstopascal)(nil)

type Wordstopascal struct {
	*RootCmd
	Flags           *flag.FlagSet
	input           string
	output          string
	jsonInput       bool
	delimiter       string
	screaming       bool
	whispering      bool
	firstUpper      bool
	firstLower      bool
	nonAlphanumeric bool
	strict          bool
	args            []string
	SubCommands     map[string]Cmd
	CommandAction   func(c *Wordstopascal) error
}

type UsageDataWordstopascal struct {
	*Wordstopascal
	Recursive bool
}

func (c *Wordstopascal) Usage() {
	err := executeUsage(os.Stderr, "wordstopascal_usage.txt", UsageDataWordstopascal{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Wordstopascal) UsageRecursive() {
	err := executeUsage(os.Stderr, "wordstopascal_usage.txt", UsageDataWordstopascal{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Wordstopascal) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "input", "i":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.input = value

			case "output", "o":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.output = value

			case "jsonInput", "json-input":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.jsonInput = b
				} else {
					c.jsonInput = true
				}

			case "delimiter", "d":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.delimiter = value

			case "screaming", "S":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.screaming = b
				} else {
					c.screaming = true
				}

			case "whispering", "w":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.whispering = b
				} else {
					c.whispering = true
				}

			case "firstUpper", "first-upper", "U":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.firstUpper = b
				} else {
					c.firstUpper = true
				}

			case "firstLower", "first-lower", "l":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.firstLower = b
				} else {
					c.firstLower = true
				}

			case "nonAlphanumeric", "non-alphanumeric", "alphanumeric", "N":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.nonAlphanumeric = b
				} else {
					c.nonAlphanumeric = true
				}

			case "strict":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.strict = b
				} else {
					c.strict = true
				}
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		} else {
			remainingArgs = append(remainingArgs, arg)
		}
	}
	// Handle vararg args
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.args = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("wordstopascal failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewWordstopascal() *Wordstopascal {
	set := flag.NewFlagSet("wordstopascal", flag.ContinueOnError)
	v := &Wordstopascal{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.input, "input", "", "Input file or - for stdin")
	set.StringVar(&v.input, "i", "", "Input file or - for stdin")

	set.StringVar(&v.output, "output", "", "Output file or - for stdout")
	set.StringVar(&v.output, "o", "", "Output file or - for stdout")

	set.BoolVar(&v.jsonInput, "json-input", false, "Input as JSON")

	set.StringVar(&v.delimiter, "delimiter", "", "Delimiter")
	set.StringVar(&v.delimiter, "d", "", "Delimiter")

	set.BoolVar(&v.screaming, "screaming", false, "Screaming mode")
	set.BoolVar(&v.screaming, "S", false, "Screaming mode")

	set.BoolVar(&v.whispering, "whispering", false, "Whispering mode")
	set.BoolVar(&v.whispering, "w", false, "Whispering mode")

	set.BoolVar(&v.firstUpper, "first-upper", false, "First char upper")
	set.BoolVar(&v.firstUpper, "U", false, "First char upper")

	set.BoolVar(&v.firstLower, "first-lower", false, "First char lower")
	set.BoolVar(&v.firstLower, "l", false, "First char lower")

	set.BoolVar(&v.nonAlphanumeric, "non-alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "N", false, "Treat non characters as delimiters")

	set.BoolVar(&v.strict, "strict", false, "Strict UTF8 mode")
	set.Usage = v.Usage

	v.CommandAction = func(c *Wordstopascal) error {

		cli.WordsToPascal(c.input, c.output, c.jsonInput, c.delimiter, c.screaming, c.whispering, c.firstUpper, c.firstLower, c.nonAlphanumeric, c.strict, c.args...)
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
