// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"github.com/arran4/strings2/cli"
)

var _ Cmd = (*Words)(nil)

type Words struct {
	*RootCmd
	Flags             *flag.FlagSet
	input             string
	output            string
	jsonOut           bool
	delimiter         string
	noSmartAcronyms   bool
	numberSplitting   bool
	nonAlphanumeric   bool
	delimiterDetector string
	acronym           []string
	acronymFromFile   []string
	strict            bool
	args              []string
	SubCommands       map[string]func() Cmd
	CommandAction     func(c *Words) error
}

type UsageDataWords struct {
	*Words
	Recursive bool
}

func (c *Words) Usage() {
	err := executeUsage(os.Stderr, "words_usage.txt", UsageDataWords{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Words) UsageRecursive() {
	err := executeUsage(os.Stderr, "words_usage.txt", UsageDataWords{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Words) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "input":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.input = value

			case "output":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.output = value

			case "jsonOut", "json":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.jsonOut = b
				} else {
					c.jsonOut = true
				}

			case "delimiter":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.delimiter = value

			case "noSmartAcronyms", "no-smart-acronyms":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.noSmartAcronyms = b
				} else {
					c.noSmartAcronyms = true
				}

			case "numberSplitting", "number-splitting":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.numberSplitting = b
				} else {
					c.numberSplitting = true
				}

			case "nonAlphanumeric", "non-alphanumeric", "alphanumeric":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.nonAlphanumeric = b
				} else {
					c.nonAlphanumeric = true
				}

			case "delimiterDetector", "delimiter-detector":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.delimiterDetector = value

			case "acronym":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.acronym = append(c.acronym, value)

			case "acronymFromFile", "acronym-from-file":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.acronymFromFile = append(c.acronymFromFile, value)

			case "strict":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.strict = b
				} else {
					c.strict = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "i" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.input = value
				}

				if char == "o" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.output = value
				}

				if char == "d" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.delimiter = value
				}

				if char == "N" {
					found = true
					c.nonAlphanumeric = true
				}

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	// Handle vararg args
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.args = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("words failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewWords() *Words {
	set := flag.NewFlagSet("words", flag.ContinueOnError)
	v := &Words{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.input, "input", "", "Input file or - for stdin")
	set.StringVar(&v.input, "i", "", "Input file or - for stdin")

	set.StringVar(&v.output, "output", "", "Output file or - for stdout")
	set.StringVar(&v.output, "o", "", "Output file or - for stdout")

	set.BoolVar(&v.jsonOut, "json", false, "Output as JSON")

	set.StringVar(&v.delimiter, "delimiter", "", "Delimiter")
	set.StringVar(&v.delimiter, "d", "", "Delimiter")

	set.BoolVar(&v.noSmartAcronyms, "no-smart-acronyms", false, "Disable smart acronyms")

	set.BoolVar(&v.numberSplitting, "number-splitting", false, "Enable number splitting")

	set.BoolVar(&v.nonAlphanumeric, "non-alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "alphanumeric", false, "Treat non characters as delimiters")
	set.BoolVar(&v.nonAlphanumeric, "N", false, "Treat non characters as delimiters")

	set.StringVar(&v.delimiterDetector, "delimiter-detector", "", "Delimiter detector expression")

	set.Var((*StringSlice)(&v.acronym), "acronym", "Acronym to preserve case")

	set.Var((*StringSlice)(&v.acronymFromFile), "acronym-from-file", "File containing acronyms to preserve case")

	set.BoolVar(&v.strict, "strict", false, "Strict UTF8 mode")
	set.Usage = v.Usage

	v.CommandAction = func(c *Words) error {

		cli.Words(c.input, c.output, c.jsonOut, c.delimiter, c.noSmartAcronyms, c.numberSplitting, c.nonAlphanumeric, c.delimiterDetector, c.acronym, c.acronymFromFile, c.strict, c.args...)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
